// This file is generated by the generate-abis script. Do not modify it manually.

import { RewardRatePoolAbi } from './RewardRatePool';
import { SENTAbi } from './SENT';
import { ServiceNodeContributionAbi } from './ServiceNodeContribution';
import { ServiceNodeContributionFactoryAbi } from './ServiceNodeContributionFactory';
import { ServiceNodeRewardsAbi } from './ServiceNodeRewards';
import { TestnetServiceNodeRewardsAbi } from './TestnetServiceNodeRewards';
import { TokenVestingNoStakingAbi } from './TokenVestingNoStaking';
import { TokenVestingStakingAbi } from './TokenVestingStaking';

export const Contracts = {
  RewardRatePool: RewardRatePoolAbi,
  Token: SENTAbi,
  ServiceNodeContribution: ServiceNodeContributionAbi,
  ServiceNodeContributionFactory: ServiceNodeContributionFactoryAbi,
  ServiceNodeRewards: ServiceNodeRewardsAbi,
  TestnetServiceNodeRewards: TestnetServiceNodeRewardsAbi,
  TokenVestingNoStaking: TokenVestingNoStakingAbi,
  TokenVestingStaking: TokenVestingStakingAbi,
} as const;
export type ContractWithAbiName = keyof typeof Contracts;
export type ContractAbis = typeof Contracts;
export {
  RewardRatePoolAbi,
  SENTAbi,
  ServiceNodeContributionAbi,
  ServiceNodeContributionFactoryAbi,
  ServiceNodeRewardsAbi,
  TestnetServiceNodeRewardsAbi,
  TokenVestingNoStakingAbi,
  TokenVestingStakingAbi,
};
