// This file is generated by the generate-abis script. Do not modify it manually.

/**
 * Compatibility alias for code that still imports the legacy testnet rewards ABI.
 */
export { ServiceNodeRewardsAbi as TestnetServiceNodeRewardsAbi } from './ServiceNodeRewards';
